// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXzV_ZKf7iWFlxUzTxU30TDlF2TINHBu0',
    appId: '1:88781154999:web:e76feacfbdc05ca6c97b32',
    messagingSenderId: '88781154999',
    projectId: 'notes-efbf1',
    authDomain: 'notes-efbf1.firebaseapp.com',
    storageBucket: 'notes-efbf1.appspot.com',
    measurementId: 'G-90WJR5VNGQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEMf_NKoJ8OZWZlxE-tu5a4Ut_ZL7ZKzU',
    appId: '1:88781154999:android:a6b53f5366893f32c97b32',
    messagingSenderId: '88781154999',
    projectId: 'notes-efbf1',
    storageBucket: 'notes-efbf1.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCR6g6rb7FmlX8J2KjC6hYm6ajFXoZujxw',
    appId: '1:88781154999:ios:25fdb6c7812fb51fc97b32',
    messagingSenderId: '88781154999',
    projectId: 'notes-efbf1',
    storageBucket: 'notes-efbf1.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR6g6rb7FmlX8J2KjC6hYm6ajFXoZujxw',
    appId: '1:88781154999:ios:25fdb6c7812fb51fc97b32',
    messagingSenderId: '88781154999',
    projectId: 'notes-efbf1',
    storageBucket: 'notes-efbf1.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXzV_ZKf7iWFlxUzTxU30TDlF2TINHBu0',
    appId: '1:88781154999:web:221ff4610628ba4cc97b32',
    messagingSenderId: '88781154999',
    projectId: 'notes-efbf1',
    authDomain: 'notes-efbf1.firebaseapp.com',
    storageBucket: 'notes-efbf1.appspot.com',
    measurementId: 'G-C323XSHVJJ',
  );

}